# ============================================== #
# UnderGroundPlus
# configuration file
# 
# auther: the_karura
# ============================================== #
worlds:
- Resorce1
- Resorce2
biome:
  FOREST:
    layer:
    - STONE
    - DIRT
    - COBBLESTONE
    floot:
    - GRASS
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - RED_ROSE
  FOREST_HILLS:
    layer:
    - STONE
    - DIRT
    - COBBLESTONE
    floot:
    - GRASS
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - RED_ROSE
  FLOWER_FOREST:
    layer:
    - STONE
    - DIRT
    - COBBLESTONE
    floot:
    - GRASS
    floot_plants:
    - AIR
    - RED_ROSE
    - RED_ROSE:1
    - RED_ROSE:2
    - RED_ROSE:3
    - RED_ROSE:4
    - RED_ROSE:5
    - RED_ROSE:6
    - RED_ROSE:7
    - RED_ROSE:8
  BIRCH_FOREST:
    layer:
    - STONE
    - DIRT
    - COBBLESTONE
    floot:
    - GRASS
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - RED_ROSE
  BIRCH_FOREST_HILLS:
    layer:
    - STONE
    - DIRT
    - COBBLESTONE
    floot:
    - GRASS
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - RED_ROSE
  BIRCH_FOREST_HILLS_MOUNTAINS:
    layer:
    - STONE
    - DIRT
    - COBBLESTONE
    floot:
    - GRASS
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - RED_ROSE
  BIRCH_FOREST_MOUNTAINS:
    layer:
    - STONE
    - DIRT
    - COBBLESTONE
    floot:
    - GRASS
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - RED_ROSE
  DESERT:
    layer:
    - STONE
    - SANDSTONE
    floot:
    - SAND
    floot_plants:
    - AIR
    - AIR
    - AIR
    - AIR
    - AIR
    - AIR
    - AIR
    - AIR
    - DEAD_BUSH
    top:
    - SANDSTONE
  DESERT_HILLS:
    layer:
    - STONE
    - SANDSTONE
    floot:
    - SAND
    top:
    - SANDSTONE
  DESERT_MOUNTAINS:
    layer:
    - STONE
    - SANDSTONE
    floot:
    - SAND
    top:
    - SANDSTONE
  JUNGLE:
    set:
      top_plants:
        min: 1
        max: 5
    layer:
    - STONE
    - DIRT
    - CLAY
    floot:
    - GRASS
    - SOUL_SAND
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
    top_plants:
    - AIR
    - VINE:15
  JUNGLE_EDGE:
    set:
      top_plants:
        min: 1
        max: 5
    layer:
    - STONE
    - DIRT
    - CLAY
    floot:
    - GRASS
    - SOUL_SAND
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
    top_plants:
    - AIR
    - VINE:15
  JUNGLE_EDGE_MOUNTAINS:
    set:
      top_plants:
        min: 1
        max: 5
    layer:
    - STONE
    - DIRT
    - CLAY
    floot:
    - GRASS
    - SOUL_SAND
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
    top_plants:
    - AIR
    - VINE:15
  JUNGLE_HILLS:
    set:
      top_plants:
        min: 1
        max: 5
    layer:
    - STONE
    - DIRT
    - CLAY
    floot:
    - GRASS
    - SOUL_SAND
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
    top_plants:
    - AIR
    - VINE:15
  JUNGLE_MOUNTAINS:
    set:
      top_plants:
        min: 1
        max: 5
    layer:
    - STONE
    - DIRT
    - CLAY
    floot:
    - GRASS
    - SOUL_SAND
    floot_plants:
    - AIR
    - LONG_GRASS:1
    - LONG_GRASS:1
    - YELLOW_FLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
    top_plants:
    - AIR
    - VINE:15
  OCEAN:
    floot:
    - GRAVEL
  DEEP_OCEAN:
    floot:
    - GRAVEL
  SWAMPLAND:
    set:
      top_plants:
        min: 1
        max: 2
    layer:
    - STONE
    - STONE
    - STONE
    - DIRT
    - CLAY
    floot:
    - GRASS
    - SOUL_SAND
    floot_plants:
    - LOMG_GRASS:1
    - LOMG_GRASS:2
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
    top_plants:
    - AIR
    - VINE:15
  SWAMPLAND_MOUNTAINS:
    set:
      top_plants:
        min: 1
        max: 2
    layer:
    - STONE
    - STONE
    - STONE
    - DIRT
    - CLAY
    floot:
    - GRASS
    - SOUL_SAND
    floot_plants:
    - LOMG_GRASS:1
    - LOMG_GRASS:2
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
    top_plants:
    - VINE:15
  ICE_PLAINS:
    floot:
    - ICE
    - ICE
    - ICE
    - ICE
    - SNOW_BLOCK
    top:
    - SNOW_BLOCK
  ICE_MOUNTAINS:
    floot:
    - ICE
    - ICE
    - ICE
    - ICE
    - SNOW_BLOCK
    top:
    - SNOW_BLOCK
  MUSHROOM_ISLAND:
    floot:
    - MYCEL
    floot_plants:
    - AIR
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
  MUSHROOM_SHORE:
    layer:
    - STONE
    - DIRT
    floot:
    - MYCEL
    floot_plants:
    - AIR
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    top:
    - DIRT
